logging:
  level:
    com:
      fakebili:
        debug
    root: warn

jasypt:
  mysql-base-url: fakebili-encrypt[Bc77lYfmbnsWX73/7axyv75hySsSZBzoslF4gYyVptj2MSmekBN8TJ4sDns+jQJCxjybeJPl9wiRD7oKYbMXPsqc9JUoAlazxRL2owOeaJo=]
  mysql-password: fakebili-encrypt[B5V+oH14UpQKO7W6ifhixwiZCy81PhZ3Q4pH5nCmtv+txZSjaoCmLn/7hWpeEeUns+kNPLHqd9uBuMvorij5EQ==]
  redis-host: fakebili-encrypt[Ci01aZmOYwMnV97uivjCUUoXv4U/6iPhGUUcoZkOT7kVjJIT6tSxamTXhCjdK8fZ]
  redis-password: fakebili-encrypt[elZ84p7mN7rpZezd5J7Bov4gJnHlEy+E7O5ec03xUyGqmlCvZ2dAJr5zUk6JfbLS]
  mail-username: fakebili-encrypt[vLVK42TvK+ClQGh5TwlTaQ8TdnlFEgQsPpMAbBY9Rydx5R0w6inEL7pmtNN07P8Wur/x27yGX8OpMZ5GhfS50A==]
  mail-password: fakebili-encrypt[ZlNuKvyC31TWAVx9PVE16VBnCYlriqpSyiecsWXKfwz1+1ZbZiBEBcNuXRpYPQSL4cEXdJCRrIJyAt1TsD/KuQ==]
  encryptor:
    property:
      prefix: "fakebili-encrypt["
      suffix: "]"

spring:
  application:
    name: fakebili-final
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${jasypt.mysql-base-url}/fakebili?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: ${jasypt.mysql-password}
  jackson:
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  redis:
    host: ${jasypt.redis-host}
    port: 11451
    password: ${jasypt.redis-password}
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  #邮箱基本配置
  mail:
    #配置smtp服务主机地址
    host: smtp.qq.com
    #发送者邮箱
    username: ${jasypt.mail-username}
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: ${jasypt.mail-password}
    #端口号465或587
    port: 587
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

# sa-token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid

